# @package _group_
name: unet
# --- model config ---
nch: 128
init_type: normal
loss_type: L2

# --- optimizer configs ---
optimizer: adam
lr: 0.001
alpha: 0.9
beta_1: 0.5
beta_2: 0.999
lr_policy: None

# --- masking configs ---
mask:
  add_loss_mask: True
  add_mask: True
  add_test_mask: False
  mask_fill:
  mask_overcoat: 
  mask_shape: 
  mask_w: 3
  mask_h: 3
  add_gauss: 
  mask_ratio: 0.85

  mask_mode: sinlge
  mask_category: rec
  line:
    degree: 0-90
    thickness: 4
