# @package _group_
name: unetN1
# --- model config ---
nch: 128
init_type: normal
loss_type: L2

# --- optimizer configs ---
optimizer: adam
lr: 0.001
alpha: 0.9
beta_1: 0.5
beta_2: 0.999
lr_policy: None

# --- masking configs ---
mask:
  add_loss_mask: True
  add_mask: True
  add_test_mask: False
  mask_mode: rectangle
  mask_fill:
  mask_overcoat: 
  mask_shape: 
  mask_w: 3
  mask_h: 3
  add_gauss: 
  mask_ratio: 0.85

  mode: single
  category: rec
  size: 10
  mu: 0
  sigma: 5
  color: c
  line:
    degree: 0-180
    thickness: 4
  
