seed: 999
device: cuda
is_tqdm: True
work_dir:
workname:

defaults:
  # - hydra/launcher: joblib
  - mode: debug
  - model: unet
  - dataset: mvtec
#  - log: ${defaults.1.model}_${defaults.2.dataset}
#    optional: true

log:
  output_dir:
  summary_path: 
  training_output_dir: train
  trained_model_dir: checkpoints
  vis_dir: visualize
  test_output_dir: test

hydra:
  output_subdir: config
  run:
    dir: output/${dataset.name}/${dataset.category}-${model.name}-${model.loss_type}Loss-${mode.score_type}score-nch${model.nch}-epoch${mode.num_epochs}-h${dataset.patch_h}w${dataset.patch_w}-${now:%Y%m%d%H%M}
  sweep:
    dir: output/${dataset.name}/
    subdir: ${dataset.category}-${model.name}-${model.loss_type}Loss-${mode.score_type}score-nch${model.nch}-epoch${mode.num_epochs}-h${dataset.patch_h}w${dataset.patch_w}-${now:%Y%m%d%H%M}


