# @package _group_
name: mvtec
category: wood256
data_dir: datasets/
data_info: 
img_w: 256
img_h: 256
img_nch: 3
patch_w: 256
patch_h: 256
num_workers: 4
pin_memory: True
random_split: True
batch_size: 64
test_batch_size: 1
digit: 0