# @package _group_
name: yamaha
category: flat
data_dir: datasets/
data_info:
img_w: 4608
img_h: 1024
img_nch: 3
patch_h: 256
patch_w: 256
num_workers: 4
pin_memory: True
random_split: True
batch_size: 4
digit: 0
