# @package _group_
name: yamaha
category: color_pattern_d5_crop_v2
data_dir: datasets/
data_info:
img_w: 512
img_h: 128
img_nch: 3
patch_w: 512
patch_h: 128
num_workers: 4
pin_memory: True
random_split: True
batch_size: 64
test_batch_size: 1
digit: 0
